# Swift Package Index manifest.
# https://swiftpackageindex.com/swiftpackageindex/spimanifest/documentation/spimanifest/commonusecases
version: 1
builder:
  configs:
    # Build & host the DocC documentation for both libraries on the Swift Package Index.
    - documentation_targets: [CommentRelayCore, CommentRelayUI]
